### obtener lista de alumnos
GET http://localhost:8080/api/alumnos/obtener
Content-Type: application/json

### inicio de sesión
POST http://localhost:8080/api/alumno/verificacion
Content-Type: application/json

{
  "numeroCuenta": "20248570785",
  "contrasena": "doriansamantha"
}

### crea un estudiante
POST http://localhost:8080/api/alumnos/crear
Content-Type: application/json

{
  "nombre": "primernombre segundonombre",
  "apellidos": "pri segu",
  "direccion": "FM",
  "sexo": false,
  "contrasena": "hhholanuevo1234"
}


### obtener expedientes
GET http://localhost:8080/api/expediente/alumnos/obtener

### obtener por correo
GET http://localhost:8080/api/alumno/correo/caflores@unah.hn

### obtener por id
GET http://localhost:8080/api/alumnos/20240070497

### crear un empleado de registro
POST http://localhost:8080/api/matricula/empleado/crear
Content-Type: application/json

{
  "idEmpleado": 1,
  "dni": "0801199025000",
  "nombre": "nombre empleado",
  "apellido": "empleado apellido", 
  "direccion": "carrizal",
  "telefono": "11223344",
  "sexo": true,
  "contrasena": "contrasena",
  "fechaContratacion": "2023-03-03",
  "clave": "112200",
  "idExpediente": 0
}

### obtiene empleado por id
GET http://localhost:8080/api/matricula/empleado/1234

### registrar carrera
POST http://localhost:8080/api/matricula/carreras/registrar
Content-Type: application/json

{
  "nombre": "INGENIERIA SISTEMAS",
  "coordinador": "20221001802"
}

### crear docente sin foto
POST http://localhost:8080/api/matricula/docente/guardar
Content-Type: multipart/form-data 

{
  "nombre": "erick vladimir",
  "apellido": "coello baca",
  "especializacion": "software",
  "contrasena": "contrasena",
  "sexo": true,
  "coordinador": false,
  "departamento": "copán"
}

### crear edificio
POST http://localhost:8080/api/edificio/crear
Content-Type: application/json

{
  "nombre": "B2",
  "numeroPisos": 4
}


### obtener edificios
GET http://localhost:8080/api/edificio/obtener/edificios