### obtener lista de alumnos
GET http://localhost:8080/api/alumnos/obtener
Content-Type: application/json

### inicio de sesión
POST http://localhost:8080/api/alumno/verificacion
Content-Type: application/json

{
  "numeroCuenta": "20248570785",
  "contraseña": "doriansamantha"
}

### crea un estudiante
POST http://localhost:8080/api/alumnos/crear
Content-Type: application/json

{
  "nombre": "primernombre segundonombre",
  "apellidos": "pri segu",
  "direccion": "FM",
  "sexo": false,
  "contrasena": "hhholanuevo1234"
}


### obtener expedientes
GET http://localhost:8080/api/expediente/alumnos/obtener

### obtener por correo
GET http://localhost:8080/api/alumno/correo/caflores@unah.hn

### obtener por id
GET http://localhost:8080/api/alumnos/20240070497